---
# tasks file for jenkins/

- name: add jenkins repo
  become: yes
  copy: src=jenkins.repo
        dest=/etc/yum.repos.d/jenkins.repo
        owner=root
        group=root
        mode=0644

- name: add jenkins key
  become: yes
  copy: src=jenkins-ci.org.key
        dest=/root/jenkins-ci.org.key
        owner=root
        group=root
        mode=0600

- name: import jenkins key
  become: yes
  command: rpm --import /root/jenkins-ci.org.key

- name: remove current java
  yum: name=java
       state=absent

- name: install jenkins java dependency
  yum: name=java-1.7.0-openjdk
       state=present

- name: install jenkins
  yum: name=jenkins
       state=latest
